name: Fix formatting

on:
  push:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --frozen-lockfile
      - name: Fix all files
        run: yarn fix
      - name: Commit changes
        run: |
          FILE_CHANGED=$(git diff src/Virgil.vfj)
          if [ ! -z "${FILE_CHANGED}" ]; then
            git config --global user.name 'Excalidraw Bot'
            git config --global user.email 'bot@excalidraw.com'
            git add .
            git commit -am "Auto commit: Format and cleanup"
            git push
          fi
